// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/dockerapi/models"
)

// ContainerCreateReader is a Reader for the ContainerCreate structure.
type ContainerCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewContainerCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewContainerCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewContainerCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewContainerCreateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewContainerCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewContainerCreateCreated creates a ContainerCreateCreated with default headers values
func NewContainerCreateCreated() *ContainerCreateCreated {
	return &ContainerCreateCreated{}
}

/*ContainerCreateCreated handles this case with default header values.

Container created successfully
*/
type ContainerCreateCreated struct {
	Payload *ContainerCreateCreatedBody
}

func (o *ContainerCreateCreated) Error() string {
	return fmt.Sprintf("[POST /containers/create][%d] containerCreateCreated  %+v", 201, o.Payload)
}

func (o *ContainerCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ContainerCreateCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerCreateBadRequest creates a ContainerCreateBadRequest with default headers values
func NewContainerCreateBadRequest() *ContainerCreateBadRequest {
	return &ContainerCreateBadRequest{}
}

/*ContainerCreateBadRequest handles this case with default header values.

bad parameter
*/
type ContainerCreateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *ContainerCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /containers/create][%d] containerCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ContainerCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerCreateNotFound creates a ContainerCreateNotFound with default headers values
func NewContainerCreateNotFound() *ContainerCreateNotFound {
	return &ContainerCreateNotFound{}
}

/*ContainerCreateNotFound handles this case with default header values.

no such container
*/
type ContainerCreateNotFound struct {
	Payload *models.ErrorResponse
}

func (o *ContainerCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /containers/create][%d] containerCreateNotFound  %+v", 404, o.Payload)
}

func (o *ContainerCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerCreateConflict creates a ContainerCreateConflict with default headers values
func NewContainerCreateConflict() *ContainerCreateConflict {
	return &ContainerCreateConflict{}
}

/*ContainerCreateConflict handles this case with default header values.

conflict
*/
type ContainerCreateConflict struct {
	Payload *models.ErrorResponse
}

func (o *ContainerCreateConflict) Error() string {
	return fmt.Sprintf("[POST /containers/create][%d] containerCreateConflict  %+v", 409, o.Payload)
}

func (o *ContainerCreateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerCreateInternalServerError creates a ContainerCreateInternalServerError with default headers values
func NewContainerCreateInternalServerError() *ContainerCreateInternalServerError {
	return &ContainerCreateInternalServerError{}
}

/*ContainerCreateInternalServerError handles this case with default header values.

server error
*/
type ContainerCreateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ContainerCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /containers/create][%d] containerCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *ContainerCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ContainerCreateBody container create body
swagger:model ContainerCreateBody
*/
type ContainerCreateBody struct {
	models.ContainerConfig

	// host config
	HostConfig *models.HostConfig `json:"HostConfig,omitempty"`

	// networking config
	NetworkingConfig *ContainerCreateParamsBodyAO1NetworkingConfig `json:"NetworkingConfig,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ContainerCreateBody) UnmarshalJSON(raw []byte) error {
	// ContainerCreateParamsBodyAO0
	var containerCreateParamsBodyAO0 models.ContainerConfig
	if err := swag.ReadJSON(raw, &containerCreateParamsBodyAO0); err != nil {
		return err
	}
	o.ContainerConfig = containerCreateParamsBodyAO0

	// ContainerCreateParamsBodyAO1
	var dataContainerCreateParamsBodyAO1 struct {
		HostConfig *models.HostConfig `json:"HostConfig,omitempty"`

		NetworkingConfig *ContainerCreateParamsBodyAO1NetworkingConfig `json:"NetworkingConfig,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataContainerCreateParamsBodyAO1); err != nil {
		return err
	}

	o.HostConfig = dataContainerCreateParamsBodyAO1.HostConfig

	o.NetworkingConfig = dataContainerCreateParamsBodyAO1.NetworkingConfig

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ContainerCreateBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	containerCreateParamsBodyAO0, err := swag.WriteJSON(o.ContainerConfig)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, containerCreateParamsBodyAO0)

	var dataContainerCreateParamsBodyAO1 struct {
		HostConfig *models.HostConfig `json:"HostConfig,omitempty"`

		NetworkingConfig *ContainerCreateParamsBodyAO1NetworkingConfig `json:"NetworkingConfig,omitempty"`
	}

	dataContainerCreateParamsBodyAO1.HostConfig = o.HostConfig

	dataContainerCreateParamsBodyAO1.NetworkingConfig = o.NetworkingConfig

	jsonDataContainerCreateParamsBodyAO1, errContainerCreateParamsBodyAO1 := swag.WriteJSON(dataContainerCreateParamsBodyAO1)
	if errContainerCreateParamsBodyAO1 != nil {
		return nil, errContainerCreateParamsBodyAO1
	}
	_parts = append(_parts, jsonDataContainerCreateParamsBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this container create body
func (o *ContainerCreateBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.ContainerConfig
	if err := o.ContainerConfig.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHostConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNetworkingConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ContainerCreateBody) validateHostConfig(formats strfmt.Registry) error {

	if swag.IsZero(o.HostConfig) { // not required
		return nil
	}

	if o.HostConfig != nil {
		if err := o.HostConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "HostConfig")
			}
			return err
		}
	}

	return nil
}

func (o *ContainerCreateBody) validateNetworkingConfig(formats strfmt.Registry) error {

	if swag.IsZero(o.NetworkingConfig) { // not required
		return nil
	}

	if o.NetworkingConfig != nil {
		if err := o.NetworkingConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "NetworkingConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ContainerCreateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ContainerCreateBody) UnmarshalBinary(b []byte) error {
	var res ContainerCreateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ContainerCreateCreatedBody ContainerCreateResponse
//
// OK response to ContainerCreate operation
swagger:model ContainerCreateCreatedBody
*/
type ContainerCreateCreatedBody struct {

	// The ID of the created container
	// Required: true
	ID string `json:"Id"`

	// Warnings encountered when creating the container
	// Required: true
	Warnings []string `json:"Warnings"`
}

// Validate validates this container create created body
func (o *ContainerCreateCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateWarnings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ContainerCreateCreatedBody) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("containerCreateCreated"+"."+"Id", "body", string(o.ID)); err != nil {
		return err
	}

	return nil
}

func (o *ContainerCreateCreatedBody) validateWarnings(formats strfmt.Registry) error {

	if err := validate.Required("containerCreateCreated"+"."+"Warnings", "body", o.Warnings); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ContainerCreateCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ContainerCreateCreatedBody) UnmarshalBinary(b []byte) error {
	var res ContainerCreateCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ContainerCreateParamsBodyAO1NetworkingConfig This container's networking configuration.
swagger:model ContainerCreateParamsBodyAO1NetworkingConfig
*/
type ContainerCreateParamsBodyAO1NetworkingConfig struct {

	// A mapping of network name to endpoint configuration for that network.
	EndpointsConfig map[string]models.EndpointSettings `json:"EndpointsConfig,omitempty"`
}

// Validate validates this container create params body a o1 networking config
func (o *ContainerCreateParamsBodyAO1NetworkingConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEndpointsConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ContainerCreateParamsBodyAO1NetworkingConfig) validateEndpointsConfig(formats strfmt.Registry) error {

	if swag.IsZero(o.EndpointsConfig) { // not required
		return nil
	}

	for k := range o.EndpointsConfig {

		if err := validate.Required("body"+"."+"NetworkingConfig"+"."+"EndpointsConfig"+"."+k, "body", o.EndpointsConfig[k]); err != nil {
			return err
		}
		if val, ok := o.EndpointsConfig[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ContainerCreateParamsBodyAO1NetworkingConfig) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ContainerCreateParamsBodyAO1NetworkingConfig) UnmarshalBinary(b []byte) error {
	var res ContainerCreateParamsBodyAO1NetworkingConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
