// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContainerResizeParams creates a new ContainerResizeParams object
// with the default values initialized.
func NewContainerResizeParams() *ContainerResizeParams {
	var ()
	return &ContainerResizeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContainerResizeParamsWithTimeout creates a new ContainerResizeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContainerResizeParamsWithTimeout(timeout time.Duration) *ContainerResizeParams {
	var ()
	return &ContainerResizeParams{

		timeout: timeout,
	}
}

// NewContainerResizeParamsWithContext creates a new ContainerResizeParams object
// with the default values initialized, and the ability to set a context for a request
func NewContainerResizeParamsWithContext(ctx context.Context) *ContainerResizeParams {
	var ()
	return &ContainerResizeParams{

		Context: ctx,
	}
}

// NewContainerResizeParamsWithHTTPClient creates a new ContainerResizeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContainerResizeParamsWithHTTPClient(client *http.Client) *ContainerResizeParams {
	var ()
	return &ContainerResizeParams{
		HTTPClient: client,
	}
}

/*ContainerResizeParams contains all the parameters to send to the API endpoint
for the container resize operation typically these are written to a http.Request
*/
type ContainerResizeParams struct {

	/*H
	  Height of the tty session in characters

	*/
	H *int64
	/*ID
	  ID or name of the container

	*/
	ID string
	/*W
	  Width of the tty session in characters

	*/
	W *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the container resize params
func (o *ContainerResizeParams) WithTimeout(timeout time.Duration) *ContainerResizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the container resize params
func (o *ContainerResizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the container resize params
func (o *ContainerResizeParams) WithContext(ctx context.Context) *ContainerResizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the container resize params
func (o *ContainerResizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the container resize params
func (o *ContainerResizeParams) WithHTTPClient(client *http.Client) *ContainerResizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the container resize params
func (o *ContainerResizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithH adds the h to the container resize params
func (o *ContainerResizeParams) WithH(h *int64) *ContainerResizeParams {
	o.SetH(h)
	return o
}

// SetH adds the h to the container resize params
func (o *ContainerResizeParams) SetH(h *int64) {
	o.H = h
}

// WithID adds the id to the container resize params
func (o *ContainerResizeParams) WithID(id string) *ContainerResizeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the container resize params
func (o *ContainerResizeParams) SetID(id string) {
	o.ID = id
}

// WithW adds the w to the container resize params
func (o *ContainerResizeParams) WithW(w *int64) *ContainerResizeParams {
	o.SetW(w)
	return o
}

// SetW adds the w to the container resize params
func (o *ContainerResizeParams) SetW(w *int64) {
	o.W = w
}

// WriteToRequest writes these params to a swagger request
func (o *ContainerResizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.H != nil {

		// query param h
		var qrH int64
		if o.H != nil {
			qrH = *o.H
		}
		qH := swag.FormatInt64(qrH)
		if qH != "" {
			if err := r.SetQueryParam("h", qH); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.W != nil {

		// query param w
		var qrW int64
		if o.W != nil {
			qrW = *o.W
		}
		qW := swag.FormatInt64(qrW)
		if qW != "" {
			if err := r.SetQueryParam("w", qW); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
