// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContainerUpdateParams creates a new ContainerUpdateParams object
// with the default values initialized.
func NewContainerUpdateParams() *ContainerUpdateParams {
	var ()
	return &ContainerUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContainerUpdateParamsWithTimeout creates a new ContainerUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContainerUpdateParamsWithTimeout(timeout time.Duration) *ContainerUpdateParams {
	var ()
	return &ContainerUpdateParams{

		timeout: timeout,
	}
}

// NewContainerUpdateParamsWithContext creates a new ContainerUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewContainerUpdateParamsWithContext(ctx context.Context) *ContainerUpdateParams {
	var ()
	return &ContainerUpdateParams{

		Context: ctx,
	}
}

// NewContainerUpdateParamsWithHTTPClient creates a new ContainerUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContainerUpdateParamsWithHTTPClient(client *http.Client) *ContainerUpdateParams {
	var ()
	return &ContainerUpdateParams{
		HTTPClient: client,
	}
}

/*ContainerUpdateParams contains all the parameters to send to the API endpoint
for the container update operation typically these are written to a http.Request
*/
type ContainerUpdateParams struct {

	/*ID
	  ID or name of the container

	*/
	ID string
	/*Update*/
	Update ContainerUpdateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the container update params
func (o *ContainerUpdateParams) WithTimeout(timeout time.Duration) *ContainerUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the container update params
func (o *ContainerUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the container update params
func (o *ContainerUpdateParams) WithContext(ctx context.Context) *ContainerUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the container update params
func (o *ContainerUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the container update params
func (o *ContainerUpdateParams) WithHTTPClient(client *http.Client) *ContainerUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the container update params
func (o *ContainerUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the container update params
func (o *ContainerUpdateParams) WithID(id string) *ContainerUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the container update params
func (o *ContainerUpdateParams) SetID(id string) {
	o.ID = id
}

// WithUpdate adds the update to the container update params
func (o *ContainerUpdateParams) WithUpdate(update ContainerUpdateBody) *ContainerUpdateParams {
	o.SetUpdate(update)
	return o
}

// SetUpdate adds the update to the container update params
func (o *ContainerUpdateParams) SetUpdate(update ContainerUpdateBody) {
	o.Update = update
}

// WriteToRequest writes these params to a swagger request
func (o *ContainerUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Update); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
