// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// SettingsInspectReader is a Reader for the SettingsInspect structure.
type SettingsInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettingsInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSettingsInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewSettingsInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSettingsInspectOK creates a SettingsInspectOK with default headers values
func NewSettingsInspectOK() *SettingsInspectOK {
	return &SettingsInspectOK{}
}

/*SettingsInspectOK handles this case with default header values.

Success
*/
type SettingsInspectOK struct {
	Payload *models.Settings
}

func (o *SettingsInspectOK) Error() string {
	return fmt.Sprintf("[GET /settings][%d] settingsInspectOK  %+v", 200, o.Payload)
}

func (o *SettingsInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Settings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSettingsInspectInternalServerError creates a SettingsInspectInternalServerError with default headers values
func NewSettingsInspectInternalServerError() *SettingsInspectInternalServerError {
	return &SettingsInspectInternalServerError{}
}

/*SettingsInspectInternalServerError handles this case with default header values.

Server error
*/
type SettingsInspectInternalServerError struct {
	Payload *models.GenericError
}

func (o *SettingsInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /settings][%d] settingsInspectInternalServerError  %+v", 500, o.Payload)
}

func (o *SettingsInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
