// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndpointDeleteParams creates a new EndpointDeleteParams object
// with the default values initialized.
func NewEndpointDeleteParams() *EndpointDeleteParams {
	var ()
	return &EndpointDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndpointDeleteParamsWithTimeout creates a new EndpointDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndpointDeleteParamsWithTimeout(timeout time.Duration) *EndpointDeleteParams {
	var ()
	return &EndpointDeleteParams{

		timeout: timeout,
	}
}

// NewEndpointDeleteParamsWithContext creates a new EndpointDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndpointDeleteParamsWithContext(ctx context.Context) *EndpointDeleteParams {
	var ()
	return &EndpointDeleteParams{

		Context: ctx,
	}
}

// NewEndpointDeleteParamsWithHTTPClient creates a new EndpointDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndpointDeleteParamsWithHTTPClient(client *http.Client) *EndpointDeleteParams {
	var ()
	return &EndpointDeleteParams{
		HTTPClient: client,
	}
}

/*EndpointDeleteParams contains all the parameters to send to the API endpoint
for the endpoint delete operation typically these are written to a http.Request
*/
type EndpointDeleteParams struct {

	/*ID
	  Endpoint identifier

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the endpoint delete params
func (o *EndpointDeleteParams) WithTimeout(timeout time.Duration) *EndpointDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the endpoint delete params
func (o *EndpointDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the endpoint delete params
func (o *EndpointDeleteParams) WithContext(ctx context.Context) *EndpointDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the endpoint delete params
func (o *EndpointDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the endpoint delete params
func (o *EndpointDeleteParams) WithHTTPClient(client *http.Client) *EndpointDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the endpoint delete params
func (o *EndpointDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the endpoint delete params
func (o *EndpointDeleteParams) WithID(id int64) *EndpointDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the endpoint delete params
func (o *EndpointDeleteParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EndpointDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
