// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndpointListParams creates a new EndpointListParams object
// with the default values initialized.
func NewEndpointListParams() *EndpointListParams {

	return &EndpointListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndpointListParamsWithTimeout creates a new EndpointListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndpointListParamsWithTimeout(timeout time.Duration) *EndpointListParams {

	return &EndpointListParams{

		timeout: timeout,
	}
}

// NewEndpointListParamsWithContext creates a new EndpointListParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndpointListParamsWithContext(ctx context.Context) *EndpointListParams {

	return &EndpointListParams{

		Context: ctx,
	}
}

// NewEndpointListParamsWithHTTPClient creates a new EndpointListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndpointListParamsWithHTTPClient(client *http.Client) *EndpointListParams {

	return &EndpointListParams{
		HTTPClient: client,
	}
}

/*EndpointListParams contains all the parameters to send to the API endpoint
for the endpoint list operation typically these are written to a http.Request
*/
type EndpointListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the endpoint list params
func (o *EndpointListParams) WithTimeout(timeout time.Duration) *EndpointListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the endpoint list params
func (o *EndpointListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the endpoint list params
func (o *EndpointListParams) WithContext(ctx context.Context) *EndpointListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the endpoint list params
func (o *EndpointListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the endpoint list params
func (o *EndpointListParams) WithHTTPClient(client *http.Client) *EndpointListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the endpoint list params
func (o *EndpointListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EndpointListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
