// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// EndpointListReader is a Reader for the EndpointList structure.
type EndpointListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndpointListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewEndpointListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEndpointListOK creates a EndpointListOK with default headers values
func NewEndpointListOK() *EndpointListOK {
	return &EndpointListOK{}
}

/*EndpointListOK handles this case with default header values.

Success
*/
type EndpointListOK struct {
	Payload models.EndpointListResponse
}

func (o *EndpointListOK) Error() string {
	return fmt.Sprintf("[GET /endpoints][%d] endpointListOK  %+v", 200, o.Payload)
}

func (o *EndpointListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointListInternalServerError creates a EndpointListInternalServerError with default headers values
func NewEndpointListInternalServerError() *EndpointListInternalServerError {
	return &EndpointListInternalServerError{}
}

/*EndpointListInternalServerError handles this case with default header values.

Server error
*/
type EndpointListInternalServerError struct {
	Payload *models.GenericError
}

func (o *EndpointListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /endpoints][%d] endpointListInternalServerError  %+v", 500, o.Payload)
}

func (o *EndpointListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
