// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// EndpointJobReader is a Reader for the EndpointJob structure.
type EndpointJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndpointJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEndpointJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewEndpointJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewEndpointJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewEndpointJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEndpointJobOK creates a EndpointJobOK with default headers values
func NewEndpointJobOK() *EndpointJobOK {
	return &EndpointJobOK{}
}

/*EndpointJobOK handles this case with default header values.

Success
*/
type EndpointJobOK struct {
	Payload *models.Endpoint
}

func (o *EndpointJobOK) Error() string {
	return fmt.Sprintf("[POST /endpoints/{id}/job][%d] endpointJobOK  %+v", 200, o.Payload)
}

func (o *EndpointJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Endpoint)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointJobBadRequest creates a EndpointJobBadRequest with default headers values
func NewEndpointJobBadRequest() *EndpointJobBadRequest {
	return &EndpointJobBadRequest{}
}

/*EndpointJobBadRequest handles this case with default header values.

Invalid request
*/
type EndpointJobBadRequest struct {
	Payload *models.GenericError
}

func (o *EndpointJobBadRequest) Error() string {
	return fmt.Sprintf("[POST /endpoints/{id}/job][%d] endpointJobBadRequest  %+v", 400, o.Payload)
}

func (o *EndpointJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointJobForbidden creates a EndpointJobForbidden with default headers values
func NewEndpointJobForbidden() *EndpointJobForbidden {
	return &EndpointJobForbidden{}
}

/*EndpointJobForbidden handles this case with default header values.

Unauthorized
*/
type EndpointJobForbidden struct {
	Payload *models.GenericError
}

func (o *EndpointJobForbidden) Error() string {
	return fmt.Sprintf("[POST /endpoints/{id}/job][%d] endpointJobForbidden  %+v", 403, o.Payload)
}

func (o *EndpointJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointJobNotFound creates a EndpointJobNotFound with default headers values
func NewEndpointJobNotFound() *EndpointJobNotFound {
	return &EndpointJobNotFound{}
}

/*EndpointJobNotFound handles this case with default header values.

Endpoint not found
*/
type EndpointJobNotFound struct {
	Payload *models.GenericError
}

func (o *EndpointJobNotFound) Error() string {
	return fmt.Sprintf("[POST /endpoints/{id}/job][%d] endpointJobNotFound  %+v", 404, o.Payload)
}

func (o *EndpointJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointJobInternalServerError creates a EndpointJobInternalServerError with default headers values
func NewEndpointJobInternalServerError() *EndpointJobInternalServerError {
	return &EndpointJobInternalServerError{}
}

/*EndpointJobInternalServerError handles this case with default header values.

Server error
*/
type EndpointJobInternalServerError struct {
	Payload *models.GenericError
}

func (o *EndpointJobInternalServerError) Error() string {
	return fmt.Sprintf("[POST /endpoints/{id}/job][%d] endpointJobInternalServerError  %+v", 500, o.Payload)
}

func (o *EndpointJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
