// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRegistryDeleteParams creates a new RegistryDeleteParams object
// with the default values initialized.
func NewRegistryDeleteParams() *RegistryDeleteParams {
	var ()
	return &RegistryDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegistryDeleteParamsWithTimeout creates a new RegistryDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegistryDeleteParamsWithTimeout(timeout time.Duration) *RegistryDeleteParams {
	var ()
	return &RegistryDeleteParams{

		timeout: timeout,
	}
}

// NewRegistryDeleteParamsWithContext creates a new RegistryDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegistryDeleteParamsWithContext(ctx context.Context) *RegistryDeleteParams {
	var ()
	return &RegistryDeleteParams{

		Context: ctx,
	}
}

// NewRegistryDeleteParamsWithHTTPClient creates a new RegistryDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegistryDeleteParamsWithHTTPClient(client *http.Client) *RegistryDeleteParams {
	var ()
	return &RegistryDeleteParams{
		HTTPClient: client,
	}
}

/*RegistryDeleteParams contains all the parameters to send to the API endpoint
for the registry delete operation typically these are written to a http.Request
*/
type RegistryDeleteParams struct {

	/*ID
	  Registry identifier

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the registry delete params
func (o *RegistryDeleteParams) WithTimeout(timeout time.Duration) *RegistryDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the registry delete params
func (o *RegistryDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the registry delete params
func (o *RegistryDeleteParams) WithContext(ctx context.Context) *RegistryDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the registry delete params
func (o *RegistryDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the registry delete params
func (o *RegistryDeleteParams) WithHTTPClient(client *http.Client) *RegistryDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the registry delete params
func (o *RegistryDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the registry delete params
func (o *RegistryDeleteParams) WithID(id int64) *RegistryDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the registry delete params
func (o *RegistryDeleteParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RegistryDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
