// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// UserCreateReader is a Reader for the UserCreate structure.
type UserCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewUserCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewUserCreateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUserCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserCreateOK creates a UserCreateOK with default headers values
func NewUserCreateOK() *UserCreateOK {
	return &UserCreateOK{}
}

/*UserCreateOK handles this case with default header values.

Success
*/
type UserCreateOK struct {
	Payload *models.UserSubset
}

func (o *UserCreateOK) Error() string {
	return fmt.Sprintf("[POST /users][%d] userCreateOK  %+v", 200, o.Payload)
}

func (o *UserCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserSubset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCreateBadRequest creates a UserCreateBadRequest with default headers values
func NewUserCreateBadRequest() *UserCreateBadRequest {
	return &UserCreateBadRequest{}
}

/*UserCreateBadRequest handles this case with default header values.

Invalid request
*/
type UserCreateBadRequest struct {
	Payload *models.GenericError
}

func (o *UserCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /users][%d] userCreateBadRequest  %+v", 400, o.Payload)
}

func (o *UserCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCreateForbidden creates a UserCreateForbidden with default headers values
func NewUserCreateForbidden() *UserCreateForbidden {
	return &UserCreateForbidden{}
}

/*UserCreateForbidden handles this case with default header values.

Unauthorized
*/
type UserCreateForbidden struct {
	Payload *models.GenericError
}

func (o *UserCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /users][%d] userCreateForbidden  %+v", 403, o.Payload)
}

func (o *UserCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCreateConflict creates a UserCreateConflict with default headers values
func NewUserCreateConflict() *UserCreateConflict {
	return &UserCreateConflict{}
}

/*UserCreateConflict handles this case with default header values.

User already exists
*/
type UserCreateConflict struct {
	Payload *models.GenericError
}

func (o *UserCreateConflict) Error() string {
	return fmt.Sprintf("[POST /users][%d] userCreateConflict  %+v", 409, o.Payload)
}

func (o *UserCreateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserCreateInternalServerError creates a UserCreateInternalServerError with default headers values
func NewUserCreateInternalServerError() *UserCreateInternalServerError {
	return &UserCreateInternalServerError{}
}

/*UserCreateInternalServerError handles this case with default header values.

Server error
*/
type UserCreateInternalServerError struct {
	Payload *models.GenericError
}

func (o *UserCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users][%d] userCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *UserCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
