// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVolumeCreateParams creates a new VolumeCreateParams object
// with the default values initialized.
func NewVolumeCreateParams() *VolumeCreateParams {
	var ()
	return &VolumeCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVolumeCreateParamsWithTimeout creates a new VolumeCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVolumeCreateParamsWithTimeout(timeout time.Duration) *VolumeCreateParams {
	var ()
	return &VolumeCreateParams{

		timeout: timeout,
	}
}

// NewVolumeCreateParamsWithContext creates a new VolumeCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewVolumeCreateParamsWithContext(ctx context.Context) *VolumeCreateParams {
	var ()
	return &VolumeCreateParams{

		Context: ctx,
	}
}

// NewVolumeCreateParamsWithHTTPClient creates a new VolumeCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVolumeCreateParamsWithHTTPClient(client *http.Client) *VolumeCreateParams {
	var ()
	return &VolumeCreateParams{
		HTTPClient: client,
	}
}

/*VolumeCreateParams contains all the parameters to send to the API endpoint
for the volume create operation typically these are written to a http.Request
*/
type VolumeCreateParams struct {

	/*VolumeConfig
	  Volume configuration

	*/
	VolumeConfig VolumeCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the volume create params
func (o *VolumeCreateParams) WithTimeout(timeout time.Duration) *VolumeCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the volume create params
func (o *VolumeCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the volume create params
func (o *VolumeCreateParams) WithContext(ctx context.Context) *VolumeCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the volume create params
func (o *VolumeCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the volume create params
func (o *VolumeCreateParams) WithHTTPClient(client *http.Client) *VolumeCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the volume create params
func (o *VolumeCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVolumeConfig adds the volumeConfig to the volume create params
func (o *VolumeCreateParams) WithVolumeConfig(volumeConfig VolumeCreateBody) *VolumeCreateParams {
	o.SetVolumeConfig(volumeConfig)
	return o
}

// SetVolumeConfig adds the volumeConfig to the volume create params
func (o *VolumeCreateParams) SetVolumeConfig(volumeConfig VolumeCreateBody) {
	o.VolumeConfig = volumeConfig
}

// WriteToRequest writes these params to a swagger request
func (o *VolumeCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.VolumeConfig); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
