// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVolumeDeleteParams creates a new VolumeDeleteParams object
// with the default values initialized.
func NewVolumeDeleteParams() *VolumeDeleteParams {
	var (
		forceDefault = bool(false)
	)
	return &VolumeDeleteParams{
		Force: &forceDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewVolumeDeleteParamsWithTimeout creates a new VolumeDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVolumeDeleteParamsWithTimeout(timeout time.Duration) *VolumeDeleteParams {
	var (
		forceDefault = bool(false)
	)
	return &VolumeDeleteParams{
		Force: &forceDefault,

		timeout: timeout,
	}
}

// NewVolumeDeleteParamsWithContext creates a new VolumeDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewVolumeDeleteParamsWithContext(ctx context.Context) *VolumeDeleteParams {
	var (
		forceDefault = bool(false)
	)
	return &VolumeDeleteParams{
		Force: &forceDefault,

		Context: ctx,
	}
}

// NewVolumeDeleteParamsWithHTTPClient creates a new VolumeDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVolumeDeleteParamsWithHTTPClient(client *http.Client) *VolumeDeleteParams {
	var (
		forceDefault = bool(false)
	)
	return &VolumeDeleteParams{
		Force:      &forceDefault,
		HTTPClient: client,
	}
}

/*VolumeDeleteParams contains all the parameters to send to the API endpoint
for the volume delete operation typically these are written to a http.Request
*/
type VolumeDeleteParams struct {

	/*Force
	  Force the removal of the volume

	*/
	Force *bool
	/*Name
	  Volume name or ID

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the volume delete params
func (o *VolumeDeleteParams) WithTimeout(timeout time.Duration) *VolumeDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the volume delete params
func (o *VolumeDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the volume delete params
func (o *VolumeDeleteParams) WithContext(ctx context.Context) *VolumeDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the volume delete params
func (o *VolumeDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the volume delete params
func (o *VolumeDeleteParams) WithHTTPClient(client *http.Client) *VolumeDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the volume delete params
func (o *VolumeDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the volume delete params
func (o *VolumeDeleteParams) WithForce(force *bool) *VolumeDeleteParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the volume delete params
func (o *VolumeDeleteParams) SetForce(force *bool) {
	o.Force = force
}

// WithName adds the name to the volume delete params
func (o *VolumeDeleteParams) WithName(name string) *VolumeDeleteParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the volume delete params
func (o *VolumeDeleteParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *VolumeDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
