// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPluginSetParams creates a new PluginSetParams object
// with the default values initialized.
func NewPluginSetParams() *PluginSetParams {
	var ()
	return &PluginSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPluginSetParamsWithTimeout creates a new PluginSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPluginSetParamsWithTimeout(timeout time.Duration) *PluginSetParams {
	var ()
	return &PluginSetParams{

		timeout: timeout,
	}
}

// NewPluginSetParamsWithContext creates a new PluginSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPluginSetParamsWithContext(ctx context.Context) *PluginSetParams {
	var ()
	return &PluginSetParams{

		Context: ctx,
	}
}

// NewPluginSetParamsWithHTTPClient creates a new PluginSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPluginSetParamsWithHTTPClient(client *http.Client) *PluginSetParams {
	var ()
	return &PluginSetParams{
		HTTPClient: client,
	}
}

/*PluginSetParams contains all the parameters to send to the API endpoint
for the plugin set operation typically these are written to a http.Request
*/
type PluginSetParams struct {

	/*Body*/
	Body []string
	/*Name
	  The name of the plugin. The `:latest` tag is optional, and is the default if omitted.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the plugin set params
func (o *PluginSetParams) WithTimeout(timeout time.Duration) *PluginSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugin set params
func (o *PluginSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugin set params
func (o *PluginSetParams) WithContext(ctx context.Context) *PluginSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugin set params
func (o *PluginSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugin set params
func (o *PluginSetParams) WithHTTPClient(client *http.Client) *PluginSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugin set params
func (o *PluginSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the plugin set params
func (o *PluginSetParams) WithBody(body []string) *PluginSetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the plugin set params
func (o *PluginSetParams) SetBody(body []string) {
	o.Body = body
}

// WithName adds the name to the plugin set params
func (o *PluginSetParams) WithName(name string) *PluginSetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the plugin set params
func (o *PluginSetParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PluginSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
