// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSecretListParams creates a new SecretListParams object
// with the default values initialized.
func NewSecretListParams() *SecretListParams {
	var ()
	return &SecretListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSecretListParamsWithTimeout creates a new SecretListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSecretListParamsWithTimeout(timeout time.Duration) *SecretListParams {
	var ()
	return &SecretListParams{

		timeout: timeout,
	}
}

// NewSecretListParamsWithContext creates a new SecretListParams object
// with the default values initialized, and the ability to set a context for a request
func NewSecretListParamsWithContext(ctx context.Context) *SecretListParams {
	var ()
	return &SecretListParams{

		Context: ctx,
	}
}

// NewSecretListParamsWithHTTPClient creates a new SecretListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSecretListParamsWithHTTPClient(client *http.Client) *SecretListParams {
	var ()
	return &SecretListParams{
		HTTPClient: client,
	}
}

/*SecretListParams contains all the parameters to send to the API endpoint
for the secret list operation typically these are written to a http.Request
*/
type SecretListParams struct {

	/*Filters
	  A JSON encoded value of the filters (a `map[string][]string`) to process on the secrets list. Available filters:

	- `id=<secret id>`
	- `label=<key> or label=<key>=value`
	- `name=<secret name>`
	- `names=<secret name>`


	*/
	Filters *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the secret list params
func (o *SecretListParams) WithTimeout(timeout time.Duration) *SecretListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secret list params
func (o *SecretListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secret list params
func (o *SecretListParams) WithContext(ctx context.Context) *SecretListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secret list params
func (o *SecretListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secret list params
func (o *SecretListParams) WithHTTPClient(client *http.Client) *SecretListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secret list params
func (o *SecretListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilters adds the filters to the secret list params
func (o *SecretListParams) WithFilters(filters *string) *SecretListParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the secret list params
func (o *SecretListParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WriteToRequest writes these params to a swagger request
func (o *SecretListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
