// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DockerHubSubset docker hub subset
// swagger:model DockerHubSubset
type DockerHubSubset struct {

	// Is authentication against DockerHub enabled
	Authentication bool `json:"Authentication,omitempty"`

	// Username used to authenticate against the DockerHub
	Username string `json:"Username,omitempty"`
}

// Validate validates this docker hub subset
func (m *DockerHubSubset) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DockerHubSubset) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DockerHubSubset) UnmarshalBinary(b []byte) error {
	var res DockerHubSubset
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
