// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ResourceControlUpdateRequest resource control update request
// swagger:model ResourceControlUpdateRequest
type ResourceControlUpdateRequest struct {

	// Permit access to the associated resource to any user
	Public bool `json:"Public,omitempty"`

	// List of team identifiers with access to the associated resource
	Teams []int64 `json:"Teams"`

	// List of user identifiers with access to the associated resource
	Users []int64 `json:"Users"`
}

// Validate validates this resource control update request
func (m *ResourceControlUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceControlUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceControlUpdateRequest) UnmarshalBinary(b []byte) error {
	var res ResourceControlUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
