// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamMembershipCreateRequest team membership create request
// swagger:model TeamMembershipCreateRequest
type TeamMembershipCreateRequest struct {

	// Role for the user inside the team (1 for leader and 2 for regular member)
	// Required: true
	Role *int64 `json:"Role"`

	// Team identifier
	// Required: true
	TeamID *int64 `json:"TeamID"`

	// User identifier
	// Required: true
	UserID *int64 `json:"UserID"`
}

// Validate validates this team membership create request
func (m *TeamMembershipCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTeamID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TeamMembershipCreateRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("Role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

func (m *TeamMembershipCreateRequest) validateTeamID(formats strfmt.Registry) error {

	if err := validate.Required("TeamID", "body", m.TeamID); err != nil {
		return err
	}

	return nil
}

func (m *TeamMembershipCreateRequest) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("UserID", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TeamMembershipCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamMembershipCreateRequest) UnmarshalBinary(b []byte) error {
	var res TeamMembershipCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
