// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserPasswordCheckResponse user password check response
// swagger:model UserPasswordCheckResponse
type UserPasswordCheckResponse struct {

	// Is the password valid
	Valid bool `json:"valid,omitempty"`
}

// Validate validates this user password check response
func (m *UserPasswordCheckResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserPasswordCheckResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPasswordCheckResponse) UnmarshalBinary(b []byte) error {
	var res UserPasswordCheckResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
