// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSwarmLeaveParams creates a new SwarmLeaveParams object
// with the default values initialized.
func NewSwarmLeaveParams() *SwarmLeaveParams {
	var (
		forceDefault = bool(false)
	)
	return &SwarmLeaveParams{
		Force: &forceDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewSwarmLeaveParamsWithTimeout creates a new SwarmLeaveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSwarmLeaveParamsWithTimeout(timeout time.Duration) *SwarmLeaveParams {
	var (
		forceDefault = bool(false)
	)
	return &SwarmLeaveParams{
		Force: &forceDefault,

		timeout: timeout,
	}
}

// NewSwarmLeaveParamsWithContext creates a new SwarmLeaveParams object
// with the default values initialized, and the ability to set a context for a request
func NewSwarmLeaveParamsWithContext(ctx context.Context) *SwarmLeaveParams {
	var (
		forceDefault = bool(false)
	)
	return &SwarmLeaveParams{
		Force: &forceDefault,

		Context: ctx,
	}
}

// NewSwarmLeaveParamsWithHTTPClient creates a new SwarmLeaveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSwarmLeaveParamsWithHTTPClient(client *http.Client) *SwarmLeaveParams {
	var (
		forceDefault = bool(false)
	)
	return &SwarmLeaveParams{
		Force:      &forceDefault,
		HTTPClient: client,
	}
}

/*SwarmLeaveParams contains all the parameters to send to the API endpoint
for the swarm leave operation typically these are written to a http.Request
*/
type SwarmLeaveParams struct {

	/*Force
	  Force leave swarm, even if this is the last manager or that it will break the cluster.

	*/
	Force *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the swarm leave params
func (o *SwarmLeaveParams) WithTimeout(timeout time.Duration) *SwarmLeaveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the swarm leave params
func (o *SwarmLeaveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the swarm leave params
func (o *SwarmLeaveParams) WithContext(ctx context.Context) *SwarmLeaveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the swarm leave params
func (o *SwarmLeaveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the swarm leave params
func (o *SwarmLeaveParams) WithHTTPClient(client *http.Client) *SwarmLeaveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the swarm leave params
func (o *SwarmLeaveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the swarm leave params
func (o *SwarmLeaveParams) WithForce(force *bool) *SwarmLeaveParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the swarm leave params
func (o *SwarmLeaveParams) SetForce(force *bool) {
	o.Force = force
}

// WriteToRequest writes these params to a swagger request
func (o *SwarmLeaveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
