// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewConfigDeleteParams creates a new ConfigDeleteParams object
// with the default values initialized.
func NewConfigDeleteParams() *ConfigDeleteParams {
	var ()
	return &ConfigDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewConfigDeleteParamsWithTimeout creates a new ConfigDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewConfigDeleteParamsWithTimeout(timeout time.Duration) *ConfigDeleteParams {
	var ()
	return &ConfigDeleteParams{

		timeout: timeout,
	}
}

// NewConfigDeleteParamsWithContext creates a new ConfigDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewConfigDeleteParamsWithContext(ctx context.Context) *ConfigDeleteParams {
	var ()
	return &ConfigDeleteParams{

		Context: ctx,
	}
}

// NewConfigDeleteParamsWithHTTPClient creates a new ConfigDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewConfigDeleteParamsWithHTTPClient(client *http.Client) *ConfigDeleteParams {
	var ()
	return &ConfigDeleteParams{
		HTTPClient: client,
	}
}

/*ConfigDeleteParams contains all the parameters to send to the API endpoint
for the config delete operation typically these are written to a http.Request
*/
type ConfigDeleteParams struct {

	/*ID
	  ID of the config

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the config delete params
func (o *ConfigDeleteParams) WithTimeout(timeout time.Duration) *ConfigDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the config delete params
func (o *ConfigDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the config delete params
func (o *ConfigDeleteParams) WithContext(ctx context.Context) *ConfigDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the config delete params
func (o *ConfigDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the config delete params
func (o *ConfigDeleteParams) WithHTTPClient(client *http.Client) *ConfigDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the config delete params
func (o *ConfigDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the config delete params
func (o *ConfigDeleteParams) WithID(id string) *ConfigDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the config delete params
func (o *ConfigDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ConfigDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
