// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NetworkContainer network container
// swagger:model NetworkContainer
type NetworkContainer struct {

	// endpoint ID
	EndpointID string `json:"EndpointID,omitempty"`

	// ipv4 address
	IPV4Address string `json:"IPv4Address,omitempty"`

	// ipv6 address
	IPV6Address string `json:"IPv6Address,omitempty"`

	// mac address
	MacAddress string `json:"MacAddress,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this network container
func (m *NetworkContainer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkContainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkContainer) UnmarshalBinary(b []byte) error {
	var res NetworkContainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
