// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PeerNode Represents a peer-node in the swarm
// swagger:model PeerNode
type PeerNode struct {

	// IP address and ports at which this node can be reached.
	//
	Addr string `json:"Addr,omitempty"`

	// Unique identifier of for this node in the swarm.
	NodeID string `json:"NodeID,omitempty"`
}

// Validate validates this peer node
func (m *PeerNode) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerNode) UnmarshalBinary(b []byte) error {
	var res PeerNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
