// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Platform Platform represents the platform (Arch/OS).
//
// swagger:model Platform
type Platform struct {

	// Architecture represents the hardware architecture (for example,
	// `x86_64`).
	//
	Architecture string `json:"Architecture,omitempty"`

	// OS represents the Operating System (for example, `linux` or `windows`).
	//
	OS string `json:"OS,omitempty"`
}

// Validate validates this platform
func (m *Platform) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Platform) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Platform) UnmarshalBinary(b []byte) error {
	var res Platform
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
