// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SecretSpec secret spec
// swagger:model SecretSpec
type SecretSpec struct {

	// Base64-url-safe-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-3.2))
	// data to store as secret.
	//
	// This field is only used to _create_ a secret, and is not returned by
	// other endpoints.
	//
	Data string `json:"Data,omitempty"`

	// Name of the secrets driver used to fetch the secret's value from an external secret store
	Driver *Driver `json:"Driver,omitempty"`

	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels,omitempty"`

	// User-defined name of the secret.
	Name string `json:"Name,omitempty"`

	// Templating driver, if applicable
	//
	// Templating controls whether and how to evaluate the config payload as
	// a template. If no driver is set, no templating is used.
	//
	Templating *Driver `json:"Templating,omitempty"`
}

// Validate validates this secret spec
func (m *SecretSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDriver(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemplating(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SecretSpec) validateDriver(formats strfmt.Registry) error {

	if swag.IsZero(m.Driver) { // not required
		return nil
	}

	if m.Driver != nil {
		if err := m.Driver.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Driver")
			}
			return err
		}
	}

	return nil
}

func (m *SecretSpec) validateTemplating(formats strfmt.Registry) error {

	if swag.IsZero(m.Templating) { // not required
		return nil
	}

	if m.Templating != nil {
		if err := m.Templating.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Templating")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SecretSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretSpec) UnmarshalBinary(b []byte) error {
	var res SecretSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
