// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Swarm swarm
// swagger:model Swarm
type Swarm struct {
	ClusterInfo

	// join tokens
	JoinTokens *JoinTokens `json:"JoinTokens,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Swarm) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ClusterInfo
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ClusterInfo = aO0

	// AO1
	var dataAO1 struct {
		JoinTokens *JoinTokens `json:"JoinTokens,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.JoinTokens = dataAO1.JoinTokens

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Swarm) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ClusterInfo)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		JoinTokens *JoinTokens `json:"JoinTokens,omitempty"`
	}

	dataAO1.JoinTokens = m.JoinTokens

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this swarm
func (m *Swarm) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ClusterInfo
	if err := m.ClusterInfo.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJoinTokens(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Swarm) validateJoinTokens(formats strfmt.Registry) error {

	if swag.IsZero(m.JoinTokens) { // not required
		return nil
	}

	if m.JoinTokens != nil {
		if err := m.JoinTokens.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JoinTokens")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Swarm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Swarm) UnmarshalBinary(b []byte) error {
	var res Swarm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
