// Code generated by go-swagger; DO NOT EDIT.

package endpoint_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// EndpointGroupCreateReader is a Reader for the EndpointGroupCreate structure.
type EndpointGroupCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointGroupCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndpointGroupCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEndpointGroupCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewEndpointGroupCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEndpointGroupCreateOK creates a EndpointGroupCreateOK with default headers values
func NewEndpointGroupCreateOK() *EndpointGroupCreateOK {
	return &EndpointGroupCreateOK{}
}

/*EndpointGroupCreateOK handles this case with default header values.

Success
*/
type EndpointGroupCreateOK struct {
	Payload *models.EndpointGroup
}

func (o *EndpointGroupCreateOK) Error() string {
	return fmt.Sprintf("[POST /endpoint_groups][%d] endpointGroupCreateOK  %+v", 200, o.Payload)
}

func (o *EndpointGroupCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EndpointGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointGroupCreateBadRequest creates a EndpointGroupCreateBadRequest with default headers values
func NewEndpointGroupCreateBadRequest() *EndpointGroupCreateBadRequest {
	return &EndpointGroupCreateBadRequest{}
}

/*EndpointGroupCreateBadRequest handles this case with default header values.

Invalid request
*/
type EndpointGroupCreateBadRequest struct {
	Payload *models.GenericError
}

func (o *EndpointGroupCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /endpoint_groups][%d] endpointGroupCreateBadRequest  %+v", 400, o.Payload)
}

func (o *EndpointGroupCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointGroupCreateInternalServerError creates a EndpointGroupCreateInternalServerError with default headers values
func NewEndpointGroupCreateInternalServerError() *EndpointGroupCreateInternalServerError {
	return &EndpointGroupCreateInternalServerError{}
}

/*EndpointGroupCreateInternalServerError handles this case with default header values.

Server error
*/
type EndpointGroupCreateInternalServerError struct {
	Payload *models.GenericError
}

func (o *EndpointGroupCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /endpoint_groups][%d] endpointGroupCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *EndpointGroupCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
