// Code generated by go-swagger; DO NOT EDIT.

package endpoint_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// EndpointGroupInspectReader is a Reader for the EndpointGroupInspect structure.
type EndpointGroupInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointGroupInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndpointGroupInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEndpointGroupInspectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewEndpointGroupInspectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewEndpointGroupInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEndpointGroupInspectOK creates a EndpointGroupInspectOK with default headers values
func NewEndpointGroupInspectOK() *EndpointGroupInspectOK {
	return &EndpointGroupInspectOK{}
}

/*EndpointGroupInspectOK handles this case with default header values.

Success
*/
type EndpointGroupInspectOK struct {
	Payload *models.EndpointGroup
}

func (o *EndpointGroupInspectOK) Error() string {
	return fmt.Sprintf("[GET /endpoint_groups/{id}][%d] endpointGroupInspectOK  %+v", 200, o.Payload)
}

func (o *EndpointGroupInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EndpointGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointGroupInspectBadRequest creates a EndpointGroupInspectBadRequest with default headers values
func NewEndpointGroupInspectBadRequest() *EndpointGroupInspectBadRequest {
	return &EndpointGroupInspectBadRequest{}
}

/*EndpointGroupInspectBadRequest handles this case with default header values.

Invalid request
*/
type EndpointGroupInspectBadRequest struct {
	Payload *models.GenericError
}

func (o *EndpointGroupInspectBadRequest) Error() string {
	return fmt.Sprintf("[GET /endpoint_groups/{id}][%d] endpointGroupInspectBadRequest  %+v", 400, o.Payload)
}

func (o *EndpointGroupInspectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointGroupInspectNotFound creates a EndpointGroupInspectNotFound with default headers values
func NewEndpointGroupInspectNotFound() *EndpointGroupInspectNotFound {
	return &EndpointGroupInspectNotFound{}
}

/*EndpointGroupInspectNotFound handles this case with default header values.

EndpointGroup not found
*/
type EndpointGroupInspectNotFound struct {
	Payload *models.GenericError
}

func (o *EndpointGroupInspectNotFound) Error() string {
	return fmt.Sprintf("[GET /endpoint_groups/{id}][%d] endpointGroupInspectNotFound  %+v", 404, o.Payload)
}

func (o *EndpointGroupInspectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEndpointGroupInspectInternalServerError creates a EndpointGroupInspectInternalServerError with default headers values
func NewEndpointGroupInspectInternalServerError() *EndpointGroupInspectInternalServerError {
	return &EndpointGroupInspectInternalServerError{}
}

/*EndpointGroupInspectInternalServerError handles this case with default header values.

Server error
*/
type EndpointGroupInspectInternalServerError struct {
	Payload *models.GenericError
}

func (o *EndpointGroupInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /endpoint_groups/{id}][%d] endpointGroupInspectInternalServerError  %+v", 500, o.Payload)
}

func (o *EndpointGroupInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
