// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/dockerapi/models"
)

// BuildPruneReader is a Reader for the BuildPrune structure.
type BuildPruneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BuildPruneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBuildPruneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewBuildPruneInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBuildPruneOK creates a BuildPruneOK with default headers values
func NewBuildPruneOK() *BuildPruneOK {
	return &BuildPruneOK{}
}

/*BuildPruneOK handles this case with default header values.

No error
*/
type BuildPruneOK struct {
	Payload *BuildPruneOKBody
}

func (o *BuildPruneOK) Error() string {
	return fmt.Sprintf("[POST /build/prune][%d] buildPruneOK  %+v", 200, o.Payload)
}

func (o *BuildPruneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(BuildPruneOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildPruneInternalServerError creates a BuildPruneInternalServerError with default headers values
func NewBuildPruneInternalServerError() *BuildPruneInternalServerError {
	return &BuildPruneInternalServerError{}
}

/*BuildPruneInternalServerError handles this case with default header values.

Server error
*/
type BuildPruneInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *BuildPruneInternalServerError) Error() string {
	return fmt.Sprintf("[POST /build/prune][%d] buildPruneInternalServerError  %+v", 500, o.Payload)
}

func (o *BuildPruneInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*BuildPruneOKBody BuildPruneResponse
swagger:model BuildPruneOKBody
*/
type BuildPruneOKBody struct {

	// caches deleted
	CachesDeleted []string `json:"CachesDeleted"`

	// Disk space reclaimed in bytes
	SpaceReclaimed int64 `json:"SpaceReclaimed,omitempty"`
}

// Validate validates this build prune o k body
func (o *BuildPruneOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *BuildPruneOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BuildPruneOKBody) UnmarshalBinary(b []byte) error {
	var res BuildPruneOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
