// Code generated by go-swagger; DO NOT EDIT.

package dockerhub

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// NewDockerHubUpdateParams creates a new DockerHubUpdateParams object
// with the default values initialized.
func NewDockerHubUpdateParams() *DockerHubUpdateParams {
	var ()
	return &DockerHubUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDockerHubUpdateParamsWithTimeout creates a new DockerHubUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDockerHubUpdateParamsWithTimeout(timeout time.Duration) *DockerHubUpdateParams {
	var ()
	return &DockerHubUpdateParams{

		timeout: timeout,
	}
}

// NewDockerHubUpdateParamsWithContext creates a new DockerHubUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDockerHubUpdateParamsWithContext(ctx context.Context) *DockerHubUpdateParams {
	var ()
	return &DockerHubUpdateParams{

		Context: ctx,
	}
}

// NewDockerHubUpdateParamsWithHTTPClient creates a new DockerHubUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDockerHubUpdateParamsWithHTTPClient(client *http.Client) *DockerHubUpdateParams {
	var ()
	return &DockerHubUpdateParams{
		HTTPClient: client,
	}
}

/*DockerHubUpdateParams contains all the parameters to send to the API endpoint
for the docker hub update operation typically these are written to a http.Request
*/
type DockerHubUpdateParams struct {

	/*Body
	  DockerHub information

	*/
	Body *models.DockerHubUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the docker hub update params
func (o *DockerHubUpdateParams) WithTimeout(timeout time.Duration) *DockerHubUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the docker hub update params
func (o *DockerHubUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the docker hub update params
func (o *DockerHubUpdateParams) WithContext(ctx context.Context) *DockerHubUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the docker hub update params
func (o *DockerHubUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the docker hub update params
func (o *DockerHubUpdateParams) WithHTTPClient(client *http.Client) *DockerHubUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the docker hub update params
func (o *DockerHubUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the docker hub update params
func (o *DockerHubUpdateParams) WithBody(body *models.DockerHubUpdateRequest) *DockerHubUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the docker hub update params
func (o *DockerHubUpdateParams) SetBody(body *models.DockerHubUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DockerHubUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
