// Code generated by go-swagger; DO NOT EDIT.

package team_memberships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/acottais/portctl/portainerapi/models"
)

// NewTeamMembershipUpdateParams creates a new TeamMembershipUpdateParams object
// with the default values initialized.
func NewTeamMembershipUpdateParams() *TeamMembershipUpdateParams {
	var ()
	return &TeamMembershipUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTeamMembershipUpdateParamsWithTimeout creates a new TeamMembershipUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTeamMembershipUpdateParamsWithTimeout(timeout time.Duration) *TeamMembershipUpdateParams {
	var ()
	return &TeamMembershipUpdateParams{

		timeout: timeout,
	}
}

// NewTeamMembershipUpdateParamsWithContext creates a new TeamMembershipUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewTeamMembershipUpdateParamsWithContext(ctx context.Context) *TeamMembershipUpdateParams {
	var ()
	return &TeamMembershipUpdateParams{

		Context: ctx,
	}
}

// NewTeamMembershipUpdateParamsWithHTTPClient creates a new TeamMembershipUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTeamMembershipUpdateParamsWithHTTPClient(client *http.Client) *TeamMembershipUpdateParams {
	var ()
	return &TeamMembershipUpdateParams{
		HTTPClient: client,
	}
}

/*TeamMembershipUpdateParams contains all the parameters to send to the API endpoint
for the team membership update operation typically these are written to a http.Request
*/
type TeamMembershipUpdateParams struct {

	/*Body
	  Team membership details

	*/
	Body *models.TeamMembershipUpdateRequest
	/*ID
	  Team membership identifier

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the team membership update params
func (o *TeamMembershipUpdateParams) WithTimeout(timeout time.Duration) *TeamMembershipUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the team membership update params
func (o *TeamMembershipUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the team membership update params
func (o *TeamMembershipUpdateParams) WithContext(ctx context.Context) *TeamMembershipUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the team membership update params
func (o *TeamMembershipUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the team membership update params
func (o *TeamMembershipUpdateParams) WithHTTPClient(client *http.Client) *TeamMembershipUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the team membership update params
func (o *TeamMembershipUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the team membership update params
func (o *TeamMembershipUpdateParams) WithBody(body *models.TeamMembershipUpdateRequest) *TeamMembershipUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the team membership update params
func (o *TeamMembershipUpdateParams) SetBody(body *models.TeamMembershipUpdateRequest) {
	o.Body = body
}

// WithID adds the id to the team membership update params
func (o *TeamMembershipUpdateParams) WithID(id int64) *TeamMembershipUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the team membership update params
func (o *TeamMembershipUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TeamMembershipUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
